language: java
jdk:
- oraclejdk8
deploy:
  provider: heroku
  api_key:
    secure: iFtT0WJwEgQrCFsEd9qrZIZU9L6LbeUvHOoZncRvGVBr6CH4/leg65WDj0N1C6ZbcEbPheb0tEtkYJFc2XobgVEDOvQH5jOd1GuyyoNvqKLAcQiuT3WLOTR7pEjN0FKBXeEwTuyqwsyFW1ya0a2AaNWslNOXCkaljLgUd/GsfG1K8SSHQ8XylPAUUTDmkTvXqq8lXeD45mMZwrQg7sQkDRDFhbcMkVKy2PEztgo/9S9F5J6XEYKJwMvVB/iNIxmFCxtQwfxfO1hp13kMYsWRz9sQ2HbIEDPSbgAycYKjJ2TX1ZDaexJm5GyLVyQ5d6PpWDANj1VOsr+sa62f9oJEjHrfnp7vaYTyRbayddoVDc3Dla2hnkqxQUS91KF7jq3BGcL8EqK8fNpCtG0Q6LkHpE0TrVHh5dalErsJX8coP/Dvah+cY6R4vA+Du3cV72ijbbF8nlp7UWNxYHZ3SCgrvTb4Cl6y0nZHvVJHI9e40HspTOU/YWw4HvZ8nmg2X4WXTHhUHO6JLHVcff3WNFscM3CLgFCAKj6t5GgB+IZyq5UUDy0UdVCqYPjc9/oIigUcKGGMFVoenc3zRm/W3BH7gmb/tqE1BCoR/2GX21qu31j5Yo6Uba61HCcnY4YPfH1ARvYCgIqOpV3rM5Jt7bVil6guJh4YfTxwIBPKGU1+Qu0=
  app: whispering-river-21103
  on:
    repo: dorsradek/shiny-octo-adventure
