spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:test;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    schema: classpath:/schema.sql
  application:
    name: follow-me
  jpa:
    show-sql: true
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
jwt:
  header: Authorization
  secret: mySecret
  expiration: 604800
  route:
    authentication:
      path: auth
      refresh: refresh
---
spring:
  profiles: development
server:
  port: 8081
---
spring:
    profiles: production
    datasource:
      url: ${JDBC_DATABASE_URL}
      driver-class-name: org.postgresql.Driver
    jpa:
      hibernate:
        ddl-auto: update

#spring:
#  data:
#    mongodb:
#      uri: mongodb://localhost/test