spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:test;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    schema: classpath:/schema.sql
  application:
    name: follow-me
  jpa:
    show-sql: true
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  social:
    facebook:
      app-id: 315052835531521
      app-secret: 241537a4e158cf800047796c13e7a310
    twitter:
      app-id: gw3l0TdvUktoLJ9g6AuDauJn0
      app-secret: Bo9RPCfMHkR53Tesm7rIpJhXUatvTtrRJiq7VN3CFKnBlUs3lr
jwt:
  header: Authorization
  secret: mySecret
  expiration: 604800
  route:
    authentication:
      path: auth
      refresh: refresh
---
spring:
  profiles: development
  social:
    facebook:
      app-id: 315052835531521
      app-secret: 241537a4e158cf800047796c13e7a310
server:
  port: 8081
---
spring:
  profiles: development-db
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8081
logging:
  level: debug
---
spring:
  profiles: production
  datasource:
    url: ${JDBC_DATABASE_URL}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

#spring:jdbc:postgresql://localhost:5432/hmdb_dev
#  data:
#    mongodb:
#      uri: mongodb://localhost/test