spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:test;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    schema: classpath:/schema.sql
  application:
    name: follow-me
server:
  port: 8081

#spring:
#  data:
#    mongodb:
#      uri: mongodb://localhost/test